apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fider-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Thomas-DeOliveira/Octave.git
    targetRevision: main
    path: k8s/fider-prod/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: fider-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true